version: 2.1

jobs:
  test: # your job name
    macos:
      xcode: 13.2.1 # indicate your selected version of Xcode

    resource_class: medium+
   # parallelism: 2
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "package.json" }}
            - v2-dependencies-

      - run:
          name: Install node_modules
          command: yarn install

      - save_cache:
          key: v2-dependencies-{{ checksum "package.json" }}
          paths:
            - node_modules

      - run:
          name: Run Unit Tests
          command: xcodebuild test -scheme navapp

  build:
    macos:
      xcode: 13.2.1 # indicate your selected version of Xcode
    steps:
      - checkout
      - run:
          # build our application
          name: Build Application
          command: xcodebuild
      - run:
          # compress Xcode's build output so that it can be stored as an artifact
          name: Compress app for storage
          command: zip -r app.zip build/Release/navapp.app
      - store_artifacts: # store this build output. Read more: https://circleci.com/docs/2.0/artifacts/
          path: app.zip
          destination: app
    
workflows:
  test_build:
    jobs:
      - test
      #- build:
      #   requires:
      #     - test  